title: Huraira Khurshid
description: Database Engine Developer | PostgreSQL Internals
author: Huraira Khurshid
email: hurairakhurshid4@gmail.com
github_username: huraira213
linkedin_username: huraira-kiyani-05497429b

# Dark theme
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Custom variables
postgres_blue: "#336791"
terminal_green: "#00ff00"
code_gray: "#1e1e1e"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme